server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    add_header Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: http://localhost:4000; connect-src 'self' http://localhost:4000;";

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
    proxy_pass http://perf-api:4000;
}

}